# Generated by Django 5.1.5 on 2025-01-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('stainless_steel', 'Acero Inoxidable'), ('carbon_steel', 'Acero al Carbono')], max_length=50, unique=True, verbose_name='Tipo de Material')),
                ('density', models.FloatField(help_text='Ingrese la densidad en gramos por centímetro cúbico.', verbose_name='Densidad (g/cm³)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Densidad de Material',
                'verbose_name_plural': 'Densidades de Materiales',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, unique=True, verbose_name='RFC'),
        ),
    ]
