# Generated by Django 5.1.5 on 2025-02-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_material_prices_restructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdensity',
            name='density',
            field=models.FloatField(help_text='Ingrese la densidad en gramos por centímetro cúbico.', verbose_name='Densidad (lb/in³)'),
        ),
    ]
