# Generated by Django 5.1.5 on 2025-02-13 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_materialdensity_density'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialdensity',
            options={'ordering': ['name'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AddField(
            model_name='materialdensity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialdensity',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción opcional del material', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='materialdensity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='materialdensity',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Material'),
        ),
        migrations.AlterField(
            model_name='materialdensity',
            name='density',
            field=models.FloatField(help_text='Ingrese la densidad en libras por pulgada cúbica', verbose_name='Densidad (lb/in³)'),
        ),
        migrations.AlterField(
            model_name='materialdensity',
            name='material_type',
            field=models.CharField(blank=True, choices=[('stainless_steel', 'Acero Inoxidable'), ('carbon_steel', 'Acero al Carbono')], max_length=50, null=True, verbose_name='Tipo de Material'),
        ),
    ]
